### ISSUE TITLE
支持github markdown 上传图片？

### ISSUE THREAD

**Issue by muwenzi** [gee1k/uPic#1]
hi，未来可以支持github markdown 上传图片吗？经常用github markdown的话图片习惯上传到github

**Comment by gee1k** [comment]
🤔正在编写支持多种图床的功能。等大致功能完成的时候，我去研究研究 Github 上传

**Comment by Songkeys** [comment]
GitHub上传的话，其他图床都是靠新建一个*公开*的仓库实现的，如果仓库是私密的，图片也无法被外部访问。

比较好的办法是借用 issue 这里的图片上传功能，不知道能不能实现。

**Comment by gee1k** [comment]
@Songkeys 既然是需要外部访问，公开仓库也未尝不可吧？

**Comment by gee1k** [comment]
@muwenzi 目前 Github 和国内的码云Gitee 的支持，功能已开发完成，下个版本会发布出来。敬请期待😁

**Comment by muwenzi** [comment]
@gee1k 👍👍，github公共仓库好像还有有一个小问题就是如果以后更改了自己github用户名，那么之前的所有链接都得改。如果是issue的图片上传方式它关联的是github user id，这个比较保险，但其api好像没有对外开放，不在rest v3里面，network里面可以找到这个接口，怎么用还得深入研究一下。

**Comment by gee1k** [comment]
@muwenzi 这个之后我再研究一下，目前 最新版 v0.7.0 已经发布，新增 Github、Gitee、微博支持
