### ISSUE TITLE
[BUG]Support shortcuts "option"+something

### ISSUE THREAD

**Issue by Saafo** [gee1k/uPic#100]
**Describe the bug**
In the Preferences -> Advanced, the Shortcuts cannot be set as option+u, option+p, etc

**Screenshots**

**Version:** [e.g. 0.19.1]

**Comment by gee1k** [comment]
It's because of your other app occupancy issues, I have two computers and one is fine. The other one won't work, but I haven't found a specific app yet either due to too many apps.
