### ISSUE TITLE
请问图床设置里的“保存路径”是做什么用的？

### ISSUE THREAD

**Issue by chshouyu** [gee1k/uPic#102]
我翻遍了教程也没找到具体用法😂

> 支持 {year} {month} {day} {hour} {minute} {second} {since_second} {since_millisecond} {random} {filename} {.suffix} {suffix} {mimetype} 等变量。比如: 上传的图片为 uPic.jpg, 设定为 “uPic/{filename}{.suffix}”, 则会保存到 “uPic/uPic.jpg”。

这里的“保存”是指哪里的保存呢？
这个设置是跟某种图床有关吗？我是用的自定义图床，服务端没有获取到这个设置相关的信息

**Comment by gee1k** [comment]
自定义基本不会用到这个的，这个是各个服务商都会去根据这个路径保存文件的

**Comment by chshouyu** [comment]
感谢~
