### ISSUE TITLE
invalid request, sha wasn't supplied  [BUG]

### ISSUE THREAD

**Issue by yaakovazat** [gee1k/uPic#104]
**Describe the bug**
invalid request, sha wasn't supplied

**Screenshots**
![image](https://user-images.githubusercontent.com/8280770/81661174-8efc7300-945d-11ea-8ec9-394c49d915b2.png)

**Version:** [e.g. 22]

**Additional context**

**Comment by gee1k** [comment]
Are you using github or gitee?
If that's the case it's due to duplicate filenames, you can set saveKey in the uPic configuration to make each image have a different name. That's a good solution to the problem.

**Comment by yaakovazat** [comment]
Yes I use Github.

Thanks a lot and I will try, it seems like the source of the problem.
