### ISSUE TITLE
[New Feature] Inject system menu bar to support switching operations

### ISSUE THREAD

**Issue by BlackHole1** [gee1k/uPic#107]
**Is your feature request related to a problem? Please describe.**
Sometimes I do n’t want to put `uPic` on the system right-click menu bar, but there is no place to close it

**Describe the solution you'd like**
I hope there is a switch that allows me to choose whether to add it to the system right-click menu bar

**Describe alternatives you've considered**
none

**Additional context**
![图片](https://user-images.githubusercontent.com/8198408/82192987-52ca8600-9927-11ea-97cf-c6bf30631ca8.png)

**Comment by gee1k** [comment]
If you don't want the sub-function you can uncheck the uPic Finder extension in the settings without an additional switch.

![image](https://user-images.githubusercontent.com/12059800/84468706-12ee8880-acb2-11ea-8040-98cb68e997a4.png)
