### ISSUE TITLE
Native macOS share menu item 

### ISSUE THREAD

**Issue by ww7** [gee1k/uPic#109]
macOS have useful screenshot functionality with editings/drawing.

Would be great to have uPic quick upload  
![](https://i.imgur.com/gjscvYY.pngl)

**Comment by ww7** [comment]
And Service
![](https://i.imgur.com/NYfFNDa.png)

**Comment by gee1k** [comment]
Sorry for forgetting to reply after a long time. This feature has been updated in the App Store version

https://apps.apple.com/us/app/id1549159979
