### ISSUE TITLE
修改配置后无法保存

### ISSUE THREAD

**Issue by Chandler-Lu** [gee1k/uPic#11]
- 安装自 brew
- macOS: 10.14.5
![2019-06-28 00 39 05](https://user-images.githubusercontent.com/18322610/60284162-75356880-993d-11e9-94f5-f722bb16fba2.gif)
另：感谢添加 brew ～:smile:

**Comment by gee1k** [comment]
@Chandler-Lu 感谢，已经发现问题，正在修复

**Comment by gee1k** [comment]
# uPic v0.6.1 Release 版发布

## 🐛 Fix Bugs

- 🐛 修复新增配置时，修改信息不能保存的问题
- 🐛 修复配置界面输入框文字过长时显示会被裁减
- 🐛 修复配置时，界面会卡顿的问题

**昨天发布新版时，没有测试完整。给大家带来困扰了。抱歉🤒**
**建议所有用户都更新**

**如遇到软件内部检查更新失败，可至 https://github.com/gee1k/uPic/releases 下载最新版安装**
