### ISSUE TITLE
30 Days for an iOS Developer

### ISSUE THREAD

**Issue by gee1k** [gee1k/uPic#110]
**Twitt URL:**`https://twitter.com/geee1k/status/1266596346468790272?s=20

-------------

Hello, Apple!

I'm Svend, an Apple development enthusiast. Interest led to the development of an APP, uPic for macOS, which began in June 2019.

uPic Image, File Upload Tool, an APP that simplifies users to upload local files to Amazon S3, Imgur and other services.

uPic macOS is open-source at Github, https://github.com/gee1k/uPic. uPic has received a lot of love from users since the first version.

I started developing uPic for iOS at the suggestion of some users and opened my Apple Developer account on April 27, 2020, and then submitted uPic for iOS to the App Store. a week later it was rejected, and I started troubleshooting the problem based on the reason for the rejection and asked the iOS developer for advice. Submitted feedback after confirming that uPic for iOS was not in violation, was rejected again 2 days later and mentioned that my account would be deleted. Over the next half month, I enlisted the help of a number of friends to check for possible violations in the app and gave me multiple feedbacks hoping for further tips.

I was warned by a friend that it might be because I set the bundle id to com.svend.uPic, which is the id used by uPic for macOS when I first submitted the app. I was worried that if I wanted to upload uPic for macOS to the app store, I deleted the app and recreated an app with the bundle id com.svend.uPic.ios for submission. I have also given detailed feedback on this matter during this half month. However, any response was received.

As of today (May 30, 2020) I have received an official email from Apple Developer and my account has officially been deleted.

In the 20 days between the first rejection and the account being deleted, I never managed to get an official and effective contact with Apple Developer. The feedback channel is only available at https://developer.apple.com/contact. This feedback-only, no-result service is the complete opposite experience for the same people I experienced as an Apple device user. I totally understand Apple's strict App Store app shelf review, but people aren't perfect. We as developers and you in the review can all make mistakes, do the wrong thing, make bad judgments. I think there has to be a final solution, and currently, I'm in a state where at least some pretty good developers in China are encountering it. There doesn't seem to be an official channel to address this, and some of the more influential developers can bring it to your attention through social forums, which you may then review. What about more people like me who have little influence, but love Apple development? In what way should we get fair and open treatment? Our annual developer account fees are not cheap.

Have fun!

![ju-1](https://user-images.githubusercontent.com/12059800/83326124-f27f0100-a2a3-11ea-8683-fa51eeca2493.jpeg)
![ju-2](https://user-images.githubusercontent.com/12059800/83326125-f579f180-a2a3-11ea-8e91-a916cd451777.jpeg)
![ju-3](https://user-images.githubusercontent.com/12059800/83326127-f6128800-a2a3-11ea-9c3f-c3596686e24b.jpeg)

**Comment by kid1412621** [comment]
so that's the reason ?
<img width="430" alt="image" src="https://user-images.githubusercontent.com/26278054/83938346-02e42e00-a806-11ea-8973-b505582fcdbe.png">

**Comment by gee1k** [comment]
Yes, you can currently use the following for local signature use
`sudo codesign -force -deep -sign - /' Applications/uPic.app`

**Comment by gee1k** [comment]
solved

https://github.com/gee1k/uPic/releases/tag/v0.19.3

**Comment by ahonn** [comment]
`brew cask install upic` is still 0.19.2
 Please update the new version

**Comment by TLHorse** [comment]
```sh
sudo codesign -force -deep -sign - /' Applications/uPic.app
                                    ^
```
Why there's a quote after the slash `/`?
