### ISSUE TITLE
[BUG]提示 “uPic.app”将对您的电脑造成伤害。 您应该将它移到废纸篓。

### ISSUE THREAD

**Issue by Michael728** [gee1k/uPic#112]
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/8510410/83939161-2b235b00-a80d-11ea-9fcd-5b1e01522a9e.png)

**Version:** [e.g. 22]
v0.19.2

**Additional context**

use command `brew cask install upic` to install，but cannot open it

**Comment by LigerShuai** [comment]
**Describe the bug**
重启Mac后，报告 uPic 为恶意软件，故删除后在 Releases 页下载最新版本 dmg 文件，仍无法打开。使用 #103 的方式也不行。
**ScreenShots**
![image](https://user-images.githubusercontent.com/11848862/83943607-1906e400-a830-11ea-9362-173da82d7fbc.png)
**Version: [e.g. 22]**
MacOS 10.15.4 && uPic.dmg v0.19.2

**Comment by jackyu0915** [comment]
> **Describe the bug**
> 重启Mac后，报告 uPic 为恶意软件，故删除后在 Releases 页下载最新版本 dmg 文件，仍无法打开。使用 #103 的方式也不行。
> **ScreenShots**
> ![image](https://user-images.githubusercontent.com/11848862/83943607-1906e400-a830-11ea-9362-173da82d7fbc.png)
> **Version: [e.g. 22]**
> MacOS 10.15.4 && uPic.dmg v0.19.2

开启在隐私中开启 任何来源，10.15上还需要执行 `sudo xattr -d com.apple.quarantine /路径/upic.dmg`，然后就可以打开了。参考：https://zhuanlan.zhihu.com/p/87144420

**Comment by LigerShuai** [comment]
> > **Describe the bug**
> > 重启Mac后，报告 uPic 为恶意软件，故删除后在 Releases 页下载最新版本 dmg 文件，仍无法打开。使用 #103 的方式也不行。
> > **ScreenShots**
> > ![image](https://user-images.githubusercontent.com/11848862/83943607-1906e400-a830-11ea-9362-173da82d7fbc.png)
> > **Version: [e.g. 22]**
> > MacOS 10.15.4 && uPic.dmg v0.19.2
> 
> 开启在隐私中开启 任何来源，10.15上还需要执行 `sudo xattr -d com.apple.quarantine /路径/upic.dmg`，然后就可以打开了。参考：[https://zhuanlan.zhihu.com/p/87144420，不过这样安装完成后应用没法打开](https://zhuanlan.zhihu.com/p/87144420%EF%BC%8C%E4%B8%8D%E8%BF%87%E8%BF%99%E6%A0%B7%E5%AE%89%E8%A3%85%E5%AE%8C%E6%88%90%E5%90%8E%E5%BA%94%E7%94%A8%E6%B2%A1%E6%B3%95%E6%89%93%E5%BC%80)

使用 sudo spctl --master-disable 开启了任何来源，然后按照上述方式操作，可以打开uPic.dmg，但安装后仍无法打开uPic.app. 弹出恶意软件警告。

**Comment by Michael728** [comment]
难道uPic 真的有安全问题吗？这个到底该怎么解决呢？

**Comment by kevinkda** [comment]
@Michael728 这是不是你的开发者证书被吊销了，或者是Apple新增了某些授权请求需要用户在系统中授权

**Comment by kevinkda** [comment]
@Michael728 似乎有暂时的解决方法，操作步骤如下：
1. 覆盖恶意软件保护
应用程序 --> uPic.app --> 右键 --> 显示简介 --> CHECK 覆盖恶意软件保护
1. 采用命令行手动签名方式
（注：--sign后 有个 横杠 不能省略）
```shell
codesign --force --deep --sign - /xxx/xxx.app
```
[方法参考](https://blog.csdn.net/foreversilent/article/details/106333198)

**Comment by gee1k** [comment]
由于我的开发者账号被苹果删除，导致 uPic 的证书失效，app无法打开了，目前大家可以先使用以下命令自己本地签名一下。没有安全问题！

sudo codesign —force —deep —sign - /Applications/uPic.app

前提是需要安装 Command Line Tools 

xcode-select —install

如果还不行，就需要关闭 SIP 了

https://www.macwk.com/article/sipmac

**Comment by gee1k** [comment]
https://github.com/gee1k/uPic/releases/tag/v0.19.2_fix

**Comment by echisenyang** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> ![image](https://user-images.githubusercontent.com/8510410/83939161-2b235b00-a80d-11ea-9fcd-5b1e01522a9e.png)
> 
> **Version:** [e.g. 22]
> v0.19.2
> 
> **Additional context**
> Add any other context about the problem here.
> 
> use command `brew cask install upic` to install，but cannot open it

try this: https://github.com/gee1k/uPic/releases/tag/v0.19.2_fix

**Comment by gee1k** [comment]
更新最新版，homebrew 同步

https://github.com/gee1k/uPic/releases/tag/v0.19.3
