### ISSUE TITLE
[BUG]catalina上使用homebrew 安装后无法打开，没有任何提示信息。

### ISSUE THREAD

**Issue by jhb92** [gee1k/uPic#113]
**Describe the bug**
catalina上使用homebrew 安装后无法打开，没有任何提示信息。

**Version:** 
MACOS 10.15.5
uPIC 0.19.2

**Additional context**

**Comment by gee1k** [comment]
由于我的开发者账号被苹果删除，导致 uPic 的证书失效，app无法打开了，目前大家可以先使用以下命令自己本地签名一下。没有安全问题！

sudo codesign —force —deep —sign - /Applications/uPic.app

前提是需要安装 Command Line Tools 

xcode-select —install

如果还不行，就需要关闭 SIP 了

https://www.macwk.com/article/sipmac

**Comment by gee1k** [comment]
https://github.com/gee1k/uPic/releases/tag/v0.19.2_fix

**Comment by gee1k** [comment]
更新最新版，homebrew 同步

https://github.com/gee1k/uPic/releases/tag/v0.19.3
