### ISSUE TITLE
[BUG] img 损坏无法打开

### ISSUE THREAD

**Issue by yishuiliunian** [gee1k/uPic#114]
**Describe the bug**
无法打开release里面的 img 提示 img 损坏无法打开
**Screenshots**

**Version:** [e.g. 22]
0.19.3
**Additional context**

**Comment by gee1k** [comment]
https://github.com/gee1k/uPic/releases/tag/v0.19.2_fix

**Comment by gee1k** [comment]
https://github.com/gee1k/uPic/releases/tag/v0.19.3
