### ISSUE TITLE
[BUG] “uPic (Autoupdate).app”将对您的电脑造成伤害。 您应该将它移到废纸篓。

### ISSUE THREAD

**Issue by ninishare** [gee1k/uPic#115]
**Describe the bug**

uPic v0.19.2 升级到 v0.19.3 ，当安装更新的时候，系统弹出“uPic (Autoupdate).app”将对您的电脑造成伤害。 您应该将它移到废纸篓。如下图：

**Screenshots**

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfqnw0r46rj314o0s0aj5.jpg)

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfqnvgq9bvj30r40doq61.jpg)

**Version:** 

uPic v0.19.3

macOS Catalina 10.15.5

**Comment by underthestars-zhy** [comment]
更新后点击取消，然后重新打开

**Comment by HelperInCa** [comment]
‘brew cask upgrade uPic’

**Comment by kklives** [comment]
> brew cask upgrade uPic

正解 更新到 0.19.3 以后可以了
