### ISSUE TITLE
上传后的返回的URL缺少前缀(https://)[BUG]

### ISSUE THREAD

**Issue by nenhall** [gee1k/uPic#122]
**Describe the bug**

**Screenshots**

**Version:** [e.g. 22]

**Additional context**

**Comment by gee1k** [comment]
具体什么图床呢？是不是你在填写域名的时候漏掉了

**Comment by nenhall** [comment]
> 具体什么图床呢？是不是你在填写域名的时候漏掉了

我用的是腾讯云，填域名的时候，是没有填写前缀(https://)
那就没问题了，我以为你的会自动补全前缀的
