### ISSUE TITLE
[BUG] 上传到 minio 的时候没有设置content-type

### ISSUE THREAD

**Issue by kikyous** [gee1k/uPic#129]
**Describe the bug**
上传到minio的时候没有设置content-type，导致上传后得到的url在浏览器里打开是下载文件，而不是直接显示图片。
在minio的后台也不能预览。

**Screenshots**
正常设置了content-type 的文件，在minio后台后台识别为图片，可以预览：
![image](https://user-images.githubusercontent.com/818616/87393156-55242600-c5e0-11ea-8104-217e1103ddd3.png)

upic上传的图片没有正确的设置content-type，在后台不能识别为图片，不能预览：
![image](https://user-images.githubusercontent.com/818616/87393303-8b61a580-c5e0-11ea-8bef-fdd0c5d1b29c.png)

**Version:** [e.g. 22]

**Additional context**

**Comment by gee1k** [comment]
请更新到 v0.20.0，使用 Amazon S3 协议使用 MinIO 。
https://github.com/gee1k/uPic/releases/tag/v0.20.0
