### ISSUE TITLE
阿里云需要点击两次保存

### ISSUE THREAD

**Issue by Chandler-Lu** [gee1k/uPic#13]
> emm我又来了
- 安装自 brew
- macOS: 10.14.5
![2019-06-28 22 20 28](https://user-images.githubusercontent.com/18322610/60348962-2c3feb80-99f3-11e9-895c-bd01ccee989b.gif)

**Comment by gee1k** [comment]
@Chandler-Lu 感谢反馈，这个问题发生的原因是由于我在文本输入是做了一个节流函数来减少页面按钮刷新状态的次数，节流的间隔我设置的是0.5秒，你的手速太快了😹  下个版本我优化一下

**Comment by Chandler-Lu** [comment]
刚刚试了一下还真是，那就没啥问题了其实，毕竟一般填参数都不会这么快的～

**Comment by gee1k** [comment]
@Chandler-Lu 你好，最新版v0.7.0已经发布了，修复了这个问题。并且已经支持微博、Github、Gitee

**Comment by Chandler-Lu** [comment]
@gee1k 
感谢～话说您提交到 brewcask 的 0.7.0 版本的 sha256 似乎有问题。
我这边 release 和 brew cask 下载都是 f010dc4922ed71d1fa1b04c7b4c57ef2ea6178b6df6acdc4773de92fbc8820ba
您提交的是 c5318028ddafe369be1996f830453a779cbd468b188b43efabfc76a5213600c0

**Comment by gee1k** [comment]
@Chandler-Lu 好的，感谢。是错了，我重新提交一下

**Comment by gee1k** [comment]
现在已经好了
