### ISSUE TITLE
未来有可能支持下图片上传后，支持本地也备份吗？

### ISSUE THREAD

**Issue by codekeeperjava** [gee1k/uPic#133]
作为一个程序员，灾备意识比较强。目前用某云，不是很信赖怕某天图片有丢失，对于blog用户来说损失很大。

希望能有一个功能，可以指定本地路径文件夹，用来备份上传到远程的图片，本地的图片名和上传到远程的文件名相同即可。感谢

**Comment by jim3ma** [comment]
感觉可以做成上传到多个图床？然后增加一个自己用作备份的图床，这样就相当于备份了
