### ISSUE TITLE
[New Feature]希望可以添加上传图片时自动重命名和清除图片exif信息的功能

### ISSUE THREAD

**Issue by Moxi-nya** [gee1k/uPic#136]
感谢作者的优秀项目，软件使用体验很棒，因为个人需求，在这提出一点小小的建议。

软件在上传图片时，会保留图片在本地的原始名称，有很小的概率可能会导致图片重名或是信息泄漏。希望可以添加上传时自动将图片重命名为md5之类的功能。

2.如果在上传图片时不选择压缩，图片在上传时会保留完整的exif信息。即使选择了压缩图片，也会保留绝大部分原始exif信息。这在分享时可能会导致较严重的信息泄漏（包括完整的拍摄设备信息，甚至位置信息）。

**Comment by gee1k** [comment]
请仔细看看图片配置，里面有 保存路径可以自定义。会按照自定义规则来重命名

**Comment by JimmyLv** [comment]
@gee1k 您好，期望能在上传之前有一个弹窗，允许手动输入有意义的图片文件命名再上传。
