### ISSUE TITLE
 Github上传提示“URLSession Task with Error：无法连接到服务器"[BUG]

### ISSUE THREAD

**Issue by eric5013** [gee1k/uPic#137]
今天使用的时候单张照片也无法上传，weibo&七牛云均可用，排除网络原因，更换github token也不可用

**Screenshots**
![image](https://user-images.githubusercontent.com/8290844/88497722-c22db780-cff3-11ea-9fc7-c12dd066f3cf.png)

**Version:** 0.19.2

**Comment by gee1k** [comment]
网络问题
