### ISSUE TITLE
chevereto图床返回图片链接为null

### ISSUE THREAD

**Issue by news0762** [gee1k/uPic#139]
作者您好，感谢开发出这么好的应用。不过在使用中遇到了一个问题，烦请帮忙解决一下。
按照教程，我配置好了chevereto图床，图片上传没有问题。但是返回的图片链接有问题，都是null。请问是哪里的问题？
谢谢！

**Comment by gee1k** [comment]
你可以检查一下URL 路径:有么有写错。['image', 'url']

如果还不行，可以提供一个账号和访问地址给我。我来测试一下。发送到我邮箱 svend.jin@gmail.com
或者加微信群和 TG群
