### ISSUE TITLE
你好，考虑支持批量上传吗

### ISSUE THREAD

**Issue by wmszhe** [gee1k/uPic#14]
你好，考虑支持批量上传吗？

有时候有多张图片，每次只能上传一张，不方便

**Comment by gee1k** [comment]
@wmszhe 有计划了，后续会加上。🤟

**Comment by wmszhe** [comment]
> @wmszhe 有计划了，后续会加上。🤟

好的，辛苦了！ 
期待！

**Comment by gee1k** [comment]
@wmszhe v0.7.1 发布啦，支持批量上传了。快去试试吧

**Comment by wmszhe** [comment]
> @wmszhe v0.7.1 发布啦，支持批量上传了。快去试试吧

OK,已经用上了，感谢🙏
