### ISSUE TITLE
[BUG] Icon in mac finder does not rendering correctly when using light theme

### ISSUE THREAD

**Issue by Kimi-Gao** [gee1k/uPic#142]
**Describe the bug**
Icon in mac finder does not render correctly when using light theme

**Screenshots**
![image](https://user-images.githubusercontent.com/12554487/90303651-403df980-dee2-11ea-8c12-424acc40a87a.png)

**Version:** [e.g. 22]

0.20.0

**Comment by gee1k** [comment]
Fixed in V0.21.0
