### ISSUE TITLE
[BUG] Custom host results in bad request

### ISSUE THREAD

**Issue by veloxy** [gee1k/uPic#143]
**Describe the bug**
Since a recent update it is no longer possible to use a custom host, it would result in an error code 400 bad request. (is there a way I can see the request that is being sent?)

**Screenshots**
![upic](https://user-images.githubusercontent.com/491675/90405598-44b21000-e0a4-11ea-83e2-abf667535947.png)

![image](https://user-images.githubusercontent.com/491675/90405372-edac3b00-e0a3-11ea-9246-91d6b52f2bac.png)

**Version:** [e.g. 22]
~I'm not sure, it works on another machine which is at 0.19.5, not on the machine that's running 0.20.0~
Only broken in 0.20.0

**Additional context**
Works on previous versions, I've not changed any settings.

**Comment by gee1k** [comment]
You can check if Content-type is set. The latest version of the customization has made changes to the Content-Type, so if you don't have it in your headers, please do, and it should fix your problem!

**Comment by veloxy** [comment]
@gee1k that was indeed the case, thank you very much.

For other people stumbling into this issue, this fixed it:

![image](https://user-images.githubusercontent.com/491675/90736520-1fa0e580-e2ce-11ea-8705-82558c2043a4.png)
