### ISSUE TITLE
[BUG] version 0.20.0 custom upload returns error 500

### ISSUE THREAD

**Issue by vanishcode** [gee1k/uPic#145]
**Describe the bug**
最新版自定义上传貌似存在问题，同样的配置在0.19.6可以正常上传，0.20.0会返回500错误

version 0.20.0 custom upload returns error 500
i try an old 0.19.6 version and there is no problem

**Version:** [e.g. 0.20.0]

**Comment by gee1k** [comment]
需手动设置 Content-Type

**Comment by vanishcode** [comment]
> 需手动设置 Content-Type

十分感谢～

**Comment by hike2008** [comment]
设置了 Content-Type 还是报 500
