### ISSUE TITLE
[BUG] 上传自定义 S3 服务器失败

### ISSUE THREAD

**Issue by jim3ma** [gee1k/uPic#148]
**Describe the bug**

上传自定义 S3 服务器，Endpoint 为 https，发送的请求还是 http，导致上传失败，http 是可以的。

**Screenshots**

**Version:** [e.g. 22]

0.20.0

**Additional context**

**Comment by gee1k** [comment]
是你自定义的 endpoint 为 https 的，但是上传的时候会自动变为 http 导致失败？

**Comment by jim3ma** [comment]
是的，抓包后发现问题的
