### ISSUE TITLE
一些小问题+小建议(比如博客图片挂了)

### ISSUE THREAD

**Issue by xiebruce** [gee1k/uPic#15]
### 【隐藏bug】1、博客图片挂了
这里[https://blog.svend.cc/upic](https://blog.svend.cc/upic/)的4个gif图挂了，原因是你图片是存在gitee中，而gitee中的图片，只要超过1M，那么必须要登录gitee才能查看，否则看不了(github不存在这问题)，有可能是你电脑一直登录着gitee，所以你没发现这个问题：
![image](https://user-images.githubusercontent.com/13575500/60859179-20022c80-a244-11e9-8163-d3eb010f0bd8.png)

### 2.【吹毛求疵】有文字没汉化
在macOS设置的系统语言为英文的情况下，下图`Hosts`那个地方，在安装完后“首次”打开时，显示的是中文“图片”两字，但只要选过了其他图床，再回来它就显示`Hosts`了，并且后面一直都没问题了，如果删掉配置文件应该会重现，不过这真的是个极小的问题，而且基本上都用中文系统，应该极少人发现这个问题，既然我发现了，那我就提出来了😄：
![image](https://user-images.githubusercontent.com/13575500/60859207-445e0900-a244-11e9-9951-18802584e8e3.png)

### 3.【小问题】配置文件在哪里？
删掉重装，原来配置还在，这也是常规做法，所以配置文件在哪呢？看了一下`/Library/Application Support`和`~/Library/Application Support`都没有呀，没其它原因，就是想知道一下。

### 4.【小建议】自定义图床headers和fields的问题
首先我认为“fields”应该改成“body”，因为这是HTTP的规范，这样会更容易接受一些(只是建议哈)

另外，headers和fields应该使用标准json，而不是键值对，原因是value有可能有空格或者特殊字符，我填的时候是不是要自己把空格写成“20%”？

### 5.【功能请求】首选项窗口在程序坞显示
不在程序坞显示真的很麻烦，比如我要填参数，去别的地方复制，回来的时候窗口没了，我知道这是隐藏在当前激活窗口的后面，也可以用三指上滑或F3找到，但是我还是认为应该在程序坞有一个图标，让用户手动关闭就好，很多软件都这么做。

### 6.【功能请求】增加右击图片上传
右击图片上传这个功能真的太需要了(而且是能右击上传已选的多张图片)，我认为这比拖拽更方便一点。

### 7.【bug】快捷键上传剪贴板图片无反应
用其他的截图软件截图到剪贴板，按uPic的上传剪贴板图片的快捷键后无反应
macOS: `10.14.4 (18E226)`
uPic: `0.7.1`

**Comment by gee1k** [comment]
**非常感谢反馈!**
- 问题1：我的确没发现gitee这个问题，已经迁移到github
- 问题2：下个版本修复
- 问题3：由于目前所有的配置都是使用`UserDefaults`来做的，所以所有的配置都在`/Users/svend/Library/Preferences/com.svend.uPic.plist`里，后期有可能会把图床配置单独拎出来，并支持导出、导入图床配置
- 问题4：自定义图床，我已经在准备重构了。现在的做法设计的不够好，也不够细。有些东西还没考虑的那么完- 善。
- 问题5：这个提议很好，后期应该会加上
- 问题6：这个功能也有考虑了
- 问题7：确实是个bug，下个版本修复

**Comment by xiebruce** [comment]
好的，这个工具不错，另外我有点担心上传历史，天长日久，我上传了上千张甚至上万张，用你这方式估计不行，是不是要搞个界面专门管理历史记录？我的建议是可以用sqlite来存，然后做搜索分页，我做过一个网页版的可以参考参考：[Upload history demo](https://imgur.com/jqshl0x)。

**Comment by gee1k** [comment]
这里的上传历史可能和你想的上传历史有点偏差。这里的上传历史目的是为了防止有时候上传了文件，又临时复制别的东西去了，那么刚上传的url就丢失了。
所以这里是只保存了最近的10条记录，并不是想做一个完整的上传管理。

**Comment by xiebruce** [comment]
哦，懂

**Comment by gee1k** [comment]
@xiebruce 0.7.2 发布了

**Comment by xiebruce** [comment]
@gee1k 辛苦了！不过又发现几个问题：

1、试了`option+command+U`、`command+shift+U`、`control+shift+U`还是无法上传剪贴板中的图片：
![image](https://user-images.githubusercontent.com/13575500/61563292-1aa7ac00-aaa6-11e9-98df-d389a805af56.png)

2、当首选项界面已经打开，图标已经在Dock栏上时，如果我忘了它是打开着的，我就会去点菜单栏图标——首选项，但是这时候没反应，按理，应该要把Dock上的那个界面给弹出来的。

3、在下边这个界面中，我添加了一个header，但是什么都不填，直接点那个减号，程序会崩溃闪退：
![image](https://user-images.githubusercontent.com/13575500/61563639-031cf300-aaa7-11e9-9b60-55701063b024.png)
