### ISSUE TITLE
uPic配置码云图床失败

### ISSUE THREAD

**Issue by pptfz** [gee1k/uPic#150]
按照这个文档配置失败
https://blog.svend.cc/upic/tutorials/gitee/

在uPic中按照文档配置完码云后，点击验证报错404，确定用户名、仓库、分支(默认master)、Token(创建是按照文档中的教程来创建的)是完全正确的，但是始终报错404，说我分支不存在

原因未知

跪求解决方法

**Comment by gee1k** [comment]
经测试无问题

**Comment by gee1k** [comment]
请检查用户名、仓库名、分支、token 

例如：
![image](https://user-images.githubusercontent.com/12059800/95811368-b9709600-0d45-11eb-8fe0-90a7e14912e4.png)

**Comment by pptfz** [comment]
首先多谢回复，问题已经解决了，原因是我创建码云仓库的时候没有指定初始化
抱歉，添麻烦了


| |
pptfzo
|
|
pptfzo@163.com
|
签名由网易邮箱大师定制


在2020年10月13日 11:18，Svend<notifications@github.com> 写道：

请检查用户名、仓库名、分支、token

例如：
