### ISSUE TITLE
sm.ms图床的验证功能有误

### ISSUE THREAD

**Issue by GloryAlex** [gee1k/uPic#152]
**Describe the bug**
使用sm.ms图床在验证时，无论是匿名版还是注册用户上传图片都会报错。
但是直接保存并使用不会有问题，怀疑是验证上传的图片格式不合sm.ms的要求。

**Screenshots**
![4p8YfE67UOIvLVg](https://i.loli.net/2020/11/02/4p8YfE67UOIvLVg.png)

**Version:** [e.g. 22]
0.20.1

**Additional context**
小细节，不过会给人以误导

**Comment by gee1k** [comment]
好的，谢谢反馈
