### ISSUE TITLE
[New Feature]望增加[快速切换图床]的快捷键

### ISSUE THREAD

**Issue by EternalHXP** [gee1k/uPic#155]
# 场景
因为我会把日常的,网上文章的,学习笔记的图片分到对应文件夹,因此需要在上传时切换图床通道(使用鼠标切换比较麻烦)

# 需求
因此,希望提供全局快捷键 : 快速切换5/10个图床的快捷键

感谢!

**Comment by leafney** [comment]
这个需求可以有。
