### ISSUE TITLE
[New Feature] 高级设置里是否可以设置一下截图app？例如xnip

### ISSUE THREAD

**Issue by lunxian8** [gee1k/uPic#159]
如题

**Comment by lunxian8** [comment]
另外想请问一下为什么历史技术里面预览图片都偏黄啊？ 哈哈

**Comment by gee1k** [comment]
第三方app适配起来会有些问题，如：
1.很多app不提供命令行方式（或其他方式）供第三方app调用。
2.这些但三方截图app，都是可以截图完编辑的，第三方app无法得知什么时候编辑完成了

**Comment by lunxian8** [comment]
懂了

**Comment by lunxian8** [comment]
![image](https://user-images.githubusercontent.com/27261113/102309473-d0c93b00-3fa3-11eb-92dc-9c8650756113.png)
![image](https://user-images.githubusercontent.com/27261113/102309519-eb031900-3fa3-11eb-8598-6935c47b36de.png)

另外想问一下为啥历史图片列表都有点偏黄啊？（没啥影响 纯属好奇）

**Comment by L1cardo** [comment]
> 另外想请问一下为什么历史技术里面预览图片都偏黄啊？ 哈哈

因为你自己的图片都偏黄
