### ISSUE TITLE
希望能够设置默认图片宽度，<img src="xx" width="300px">

### ISSUE THREAD

**Issue by LossJ** [gee1k/uPic#160]
希望能够在偏好设置中设置图片的默认宽度，复制的html文本中加入width属性

**Comment by Ryziii** [comment]
同求这个feature，希望加入一个输出到粘贴板的输出格式能够自定义的功能。

**Comment by L1cardo** [comment]
> 同求这个feature，希望加入一个输出到粘贴板的字符串格式能够自定义的功能。

这个我研究一下，但是时间不保证

**Comment by gee1k** [comment]
🚀uPic for macOS v1.1.0 已在App Store更新。

- 支持完全自定义输出格式
- 新增欢迎及授权页、截图授权教程页

🚀同时 iOS 版高级内购也半价优惠（跟随 macOS 版优惠同时结束，仅剩最后3天）。

macOS 下载👉 https://apps.apple.com/cn/app/id1549159979

iOS 下载👉https://apps.apple.com/cn/app/id1510718678

V2EX地址：https://www.v2ex.com/t/747245

🙋‍♂️
	统一回复 Github 版本问题：Github 上目前所有版本都能正常使用。代码也一直是开源的。但是因为目前为了上架 App Store 改了不少东西（审核太严格了），比如磁盘授权、截图授权等等。这些改动如果直接在 Github 版本上出现反而会提高使用的复杂度。
	所以 Github 版以后如何更新目前还是一个需要考虑的问题。
	当然，App Store 版本也是有目前 Github 上没有的功能：
- 分享菜单上传（可直接从相册等等地方上传
- 上传历史数据库（以表格的形式看到自己的上传历史记录
- 支持完全自定义的输出格式

**Comment by Ryziii** [comment]
仅支持带M1芯片的Mac嘛😧

**Comment by L1cardo** [comment]
> 仅支持带M1芯片的Mac嘛😧

都支持，请下载App Store版本使用
