### ISSUE TITLE
[BUG]上传到自定义api出错

### ISSUE THREAD

**Issue by xiebruce** [gee1k/uPic#163]
uPic版本：0.21.1（当前2020.12.25 最新）

配置
![image](https://user-images.githubusercontent.com/13575500/103125734-0a4a2680-46c7-11eb-9d98-bdbdbed82ae6.png)

在api的`index.php`那边用以下代码
```php
$str = var_export($_FILES, true);
file_put_contents('/Users/bruce/Downloads/var_dump.txt', $str, FILE_APPEND);
exit;
```

自定义api是本地搭建的，而且能接收到uPic的POST请求，只不过传过来的数据是空的，没有任何数据，以前用过一个版本是可以的(不过我忘了是哪个版本了)。

**Comment by gee1k** [comment]
你可能需要在 Other fields 中定义一下请求头中的 Content-Type

**Comment by xiebruce** [comment]
可是content-type需要写什么呢？毕竟传的东西，有可能是图片、音频、视频，还有可能是其它文件，比如文本文件，压缩包，等等，而且我用网页的js写上传，看到的content-type是这样的，这根本没法写呀，这是自动的
```
multipart/form-data; boundary=----WebKitFormBoundaryc3W3Dg63qJbDzRuT
```

据测试，uPic 0.19.6 成功了 ，20以后版本全出错，可以看看0.19.6这个版本是怎么写的。

**Comment by gee1k** [comment]
content-type 写成 multipart/form-data; 就行
