### ISSUE TITLE
建议增加URL参数后缀的配置（图片处理参数）

### ISSUE THREAD

**Issue by xgblack** [gee1k/uPic#166]
建议增加URL参数后缀的配置，例如七牛云的图片处理参数，压缩图片?imageslim等
![QQ20210110-111923](https://user-images.githubusercontent.com/30540766/104113550-be89b500-5335-11eb-8ad1-f613022dcd30.png)

**Comment by gee1k** [comment]
一直都支持
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12059800/104595190-3268ec00-56ad-11eb-842e-6df991e95827.png">
