### ISSUE TITLE
[BUG] macOS 11.1 下启动了几十个进程

### ISSUE THREAD

**Issue by chhpt** [gee1k/uPic#168]
**Describe the bug**
macOS 11.1 下启动了非常多的进程

**Screenshots**
![image](https://user-images.githubusercontent.com/19288423/104690479-773d6300-573f-11eb-9f95-5f7db7f46919.png)

**Version:** [0.21.1]

**Comment by gee1k** [comment]
发现所有app都这样，暂时找不到原因。

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622143-c2472c80-5e49-11eb-882f-3414b23e583f.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622149-c8d5a400-5e49-11eb-9e6f-dc069731afa9.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622167-e60a7280-5e49-11eb-9184-c25f82eeb432.png">

**Comment by chhpt** [comment]
Got
