### ISSUE TITLE
uPic on App Store

### ISSUE THREAD

**Issue by gee1k** [gee1k/uPic#174]
🚀uPic for macOS 已在App Store更新。

- 支持完全自定义输出格式
- 新增欢迎及授权页、截图授权教程页

macOS 下载👉 https://apps.apple.com/cn/app/id1549159979

iOS 下载👉https://apps.apple.com/cn/app/id1510718678

🙋‍♂️
	统一回复 Github 版本问题：Github 上目前所有版本都能正常使用。代码也一直是开源的。但是因为目前为了上架 App Store 改了不少东西（审核太严格了），比如磁盘授权、截图授权等等。这些改动如果直接在 Github 版本上出现反而会提高使用的复杂度。
	所以 Github 版以后如何更新目前还是一个需要考虑的问题。
	当然，App Store 版本也是有目前 Github 上没有的功能：
- 分享菜单上传（可直接从相册等等地方上传
- 上传历史数据库（以表格的形式看到自己的上传历史记录
- 支持完全自定义的输出格式

**Comment by liuzhihang** [comment]
@gee1k 
在 V2 上看到的时候已经切换到 APP Store 版本。

前天更新到 1.1.1， 发现 APP Store 版本 1.1.0 配置的 github 图床，以及历史记录都不见了。

不知道是否是一个 bug

**Comment by liuzhihang** [comment]
@gee1k 注意到一个问题，AppStore 版本和 github 版本在 /Application 的名称不一样，然后调起上传服务路径就变了。 比如 Typora 的上传服务。这块能统一么？ 还是说预期就是可以同时安装两个版本
