### ISSUE TITLE
[BUG]任务管理器里好多upic访达扩展进程

### ISSUE THREAD

**Issue by wmszhe** [gee1k/uPic#176]
**Describe the bug**
任务管理器里好多upic访达扩展进程，无意间打开任务管理器看到的，upic自身没有运行

**Screenshots**
<img width="721" alt="Xnip2021-01-22_17-07-54" src="https://user-images.githubusercontent.com/13552154/105470328-614a1800-5cd4-11eb-92e9-6cfae110135a.png">

**Version:** [e.g. 22]
0.21.1

**Additional context**

**Comment by gee1k** [comment]
发现所有app都这样，暂时找不到原因。
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622142-c07d6900-5e49-11eb-85d9-736f8727dee7.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622151-ca9f6780-5e49-11eb-97bd-c2595fdb8d46.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12059800/105622166-e4d94580-5e49-11eb-99b4-c7edb0b8d277.png">
