### ISSUE TITLE
[BUG]阿里云OSS区域不全

### ISSUE THREAD

**Issue by PolarBears** [gee1k/uPic#179]
**Describe the bug**
阿里云OSS区域不全

**Version:** App Store v1.1.1(9)

**Additional context**
缺少区域：
* 华北6（乌兰察布）
* 华南2（河源）
* 华南3（广州）

**Comment by gee1k** [comment]
收到，谢谢反馈

**Comment by gee1k** [comment]
已在 v1.1.2 修复（App Store 审核中
