### ISSUE TITLE
[BUG]使用命令行上传在 uPic 数据库不显示

### ISSUE THREAD

**Issue by liuzhihang** [gee1k/uPic#183]
**Describe the bug**
当我使用命令上传图片时：

```bash
/Applications/uPic.localized/uPic.app/Contents/MacOS/uPic -o url -u "/Applications/Typora.app/Contents/Resources/TypeMark/asserts/icon/icon_512x512.png" "/Applications/Typora.app/Contents/Resources/TypeMark/asserts/icon/icon_256x256.png"
```

上面是配置 Typora 的图片服务时使用的命令，(Typora 现在还不支持 AppStore 版本）图片上传结束后，在 uPic 数据库不显示。

**Screenshots**

**Version:** [e.g. 22]

AppStore uPic V1.1.2

**Additional context**

**Comment by gee1k** [comment]
AppStore 版本是能在 Typora 中正常使用的，你是不是 Github 版也安装了。你试试先卸载两个版本，然后重新安装 AppStore 版。（记得先导出一下配置

然后上传后，历史数据库我这边测试也正常。

但是目前的确有一个问题，就是使用Typora 上传的时候，需要先把 uPic 里的输出格式选成 URL 格式（这个我后面修复一下

**Comment by liuzhihang** [comment]
@gee1k 

![image](https://user-images.githubusercontent.com/26057042/106613475-32ba2000-65a5-11eb-9a35-260152f0dcaa.png)

好了。

应该是我之前一直使用的是 github 版本，AppStore 版本出来之后，我安装了 AppStore 版本，然后就变成上面图中的样子了。

现在卸载重装，已经好了。 感谢了。

**Comment by gee1k** [comment]
对的
