### ISSUE TITLE
能不能增加在mac的自带“照片”应用中点击分享按钮上传到upic的功能

### ISSUE THREAD

**Issue by rudolph-heisenberg** [gee1k/uPic#185]
现在在mac自带的相册里面点击分分享，然后点上传

![mIFkhVwi4JHPU3T](https://i.loli.net/2021/02/07/mIFkhVwi4JHPU3T.png)
然后会提示这个
![oHUgzBSMN6fjnDe](https://i.loli.net/2021/02/07/oHUgzBSMN6fjnDe.png)
但是在系统自带的照片权限里面，并没有为upic启用的选项
![fOeVLp4rMWDFb2x](https://i.loli.net/2021/02/07/fOeVLp4rMWDFb2x.png)

我使用的是App Store版本的upic

**Comment by gee1k** [comment]
按照提示去 uPic 偏好设置中授权磁盘访问权限

<img width="455" alt="image" src="https://user-images.githubusercontent.com/12059800/108589085-9f9c2b00-7397-11eb-99e8-c619b7608c98.png">
