### ISSUE TITLE
能不能增加mac截屏的分享按钮直接上传到upic的功能

### ISSUE THREAD

**Issue by rudolph-heisenberg** [gee1k/uPic#186]
截屏之后，点击截屏的图片，右上角点击点击分享，上传到upic：
<img width="921" alt="截屏2021-02-07 下午6 30 11" src="https://user-images.githubusercontent.com/61699791/107143896-84cabf00-6972-11eb-8dc9-17d481d5f508.png">

提示如下：
<img width="380" alt="截屏2021-02-07 下午6 30 47" src="https://user-images.githubusercontent.com/61699791/107143905-9a3fe900-6972-11eb-8d58-dca68673869d.png">

我使用的是App Store版本的upic

**Comment by jarryyen** [comment]
![iShot2022-02-21 17 00 02](https://user-images.githubusercontent.com/11880312/154921867-c6e00478-0109-467e-8e23-eef6a3fc1150.png)

uPic支持快捷键截图并自动上传的功能,在这里设置一下快捷键即可.
