### ISSUE TITLE
[BUG] typora 使用 uPic 上传图片失败

### ISSUE THREAD

**Issue by alpha-baby** [gee1k/uPic#187]
**Describe the bug**

我是使用的brew 下载的uPic ,然后我配置好了阿里云的oss，但是我在配置好typora上传图片测试的时候出现错误，但是我把其中测试的命令复制到外部的终端上执行却又是正确的。

希望大佬指导下是为什么呢

**Screenshots**
![image](https://user-images.githubusercontent.com/47237632/108582319-6a7ae300-736d-11eb-85ff-891600fc41c5.png)

**Version:** [e.g. 22]

uPic 0.21.1
typora 0.9.9.36.2 (4901)

**Additional context**

**Comment by gee1k** [comment]
你检查一下你的图床配置中域名位置是不是没有加 http 或者 https

**Comment by alpha-baby** [comment]
> 你检查一下你的图床配置中域名位置是不是没有加 http 或者 https

确实，感谢大佬
