### ISSUE TITLE
[BUG]对onedrive的使用产生影响

### ISSUE THREAD

**Issue by xiayh17** [gee1k/uPic#190]
**Describe the bug**
开启upic访达扩展之后，onedrive的同步图标消失

**Screenshots**
钩上upic之后

![截屏2021-04-022.18.51](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/截屏2021-04-022.18.51.png)

如图，文档同步状态未显示

![Snipaste_2021-04-02_14-19-29](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/Snipaste_2021-04-02_14-19-29.png)

取消钩上upic则马上恢复正常

![截屏2021-04-022.19.40](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/截屏2021-04-022.19.40.png)

如图，文档的右侧出现同步状态图标

![Snipaste_2021-04-02_14-20-03](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/Snipaste_2021-04-02_14-20-03.png)

**Version:** [e.g. 22]
系统信息
![guanyubenji](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/guanyubenji.png)
软件信息
![UaYsKs](https://cdn.jsdelivr.net/gh/LengFeng00/blog-imgbed@main/uPic/UaYsKs.png)

**Comment by gee1k** [comment]
这是 macOS 的bug，这个问题在使用访达扩展时基本都会遇到。和 uPic 无关。这几年测试下来都是这样😪
