### ISSUE TITLE
上传完成后通知内容增加文件大小

### ISSUE THREAD

**Issue by rufeng2015** [gee1k/uPic#191]
原因 ： 国内使用的是gitee做图床，但是gitee对于1m以上的图片进行限制登陆后才可查看。

期望：在通知内容里显示  图片上传后大小，图片名字等配置

解决方式：
   能否增加一个配置项，能过开关配置是否在通知显示文件名称，大小，等其他信息。 实现可定制化展示通知内容。

**Comment by yuzhouwww** [comment]
你那边 gitee图床还能用，我之前还可以，现在点验证就提示失败

**Comment by rufeng2015** [comment]
> 你那边 gitee图床还能用，我之前还可以，现在点验证就提示失败

他们升级了请求方式，换github吧
