### ISSUE TITLE
[New Feature] 能否在上传图片前，让用户自行定义文件名？

### ISSUE THREAD

**Issue by realliyifei** [gee1k/uPic#192]
能否在上传图片前，自动弹出文本框，或者是其他方式，让用户快速自行定义文件名{name}？

比如，如下图的话，我想让第二个图片的文件名也定义成grid，即“2021-04-11-grid”。

<img width="206" alt="image" src="https://user-images.githubusercontent.com/32441766/114326425-bb53c000-9b02-11eb-9dbc-fb43cab6c5a9.png">

我用的host是github。

**Comment by DreamCats** [comment]
同样需要此功能
