### ISSUE TITLE
[BUG]上传自定义 S3 服务器(Scaleway)失败

### ISSUE THREAD

**Issue by newusername2022** [gee1k/uPic#193]
感谢开发。
Scaleway的三方s3无法自定义上传，错误信息是`NSXMLParserErrorDomain error 4`，填的endpoint如下。请问这是我填写的问题还是不支持？

![Xnip2021-04-15_14-22-02](https://user-images.githubusercontent.com/65371569/114823340-ebc18580-9db2-11eb-9397-7bc2535737ee.jpg)

**Comment by gee1k** [comment]
如果是标准的 S3 协议，应该是支持的
