### ISSUE TITLE
[New Feature] 上传前图片转换

### ISSUE THREAD

**Issue by bqlin** [gee1k/uPic#194]
我想要一个这样的一个功能：上传前对特定格式的图片进行转换。
背景：有些博客平台图片只支持png、jpg，但如果遇到webp格式的图片就要额外转换了。并且希望可以限制图片尺寸。
功能细节：
- 对webp图片做格式转换，日后逐步增加支持的格式；
- 用户可以选择固定的目标格式，支持多选，例如jpg｜png。程序根据图片格式自动转换，如有alpha通道则转为png。如果格式已经是用户选择的格式，则不做转换。如果用户只选择了jpg格式，则在转换时去除alpha通道，并用白色背景绘制。
- 添加最大宽度、最大高度限制，程序按需进行格式转换。

如果可以的话，这个功能我可以做好然后pull request到该仓库吗？

**Comment by gee1k** [comment]
可以呀，欢迎 PR

**Comment by bqlin** [comment]
是在哪个分支开发呢？

**Comment by gee1k** [comment]
MAS

**Comment by bqlin** [comment]
功能做好了，UI还没写，发了邮件给你，希望沟通下如何合并 PR。
