### ISSUE TITLE
[BUG] Finder 右键菜单在 Dark 模式下的视觉问题

### ISSUE THREAD

**Issue by huhuhang** [gee1k/uPic#20]
**Describe the bug**
图标显示不清楚。

**Screenshots**

![CleanShot 2019-07-30 at 11 25 58](https://user-images.githubusercontent.com/5147530/62098498-19a02700-b2bd-11e9-9eb2-8be1c6f13c13.png)

**Version:** [e.g. 22]

**Additional context**

**Comment by gee1k** [comment]
感谢反馈，下版本修复

**Comment by gee1k** [comment]
Close by [@v0.9.0](https://github.com/gee1k/uPic/releases/tag/v0.9.0)
