### ISSUE TITLE
[BUG] 重启电脑后，历史记录和设置被清除

### ISSUE THREAD

**Issue by liuzhihang** [gee1k/uPic#201]
**Describe the bug**

重启电脑后，输出格式设置、历史记录、uPic 数据库的历史全都没了

**Screenshots**

**Version:** [e.g. 22]
v1.2.0 AppStore 版本

**Additional context**

**Comment by gee1k** [comment]
应该是你用了垃圾清理软件？

**Comment by liuzhihang** [comment]
@gee1k 因为我也是不经常重启电脑，也是前几天又重启一次的时候发现的。 等我周末再重启电脑试一下。不然我就换回开源的版本。
