### ISSUE TITLE
brew can not install upic

### ISSUE THREAD

**Issue by goalidea** [gee1k/uPic#207]
why brew delete upic cask?
now we can not install upic by brew.

**Comment by gee1k** [comment]
### 1. AppStore(Recommend):

> Only AppStore is the latest version. Other installations stay at `v0.21.1'.and you can pull the code to compile and package by yourself.

 [![uPic for macOS](https://cdn.jsdelivr.net/gh/gee1k/oss@master/uPic/app-store-black.svg)](https://apps.apple.com/cn/app/id1549159979)


### 2.Homebrew
```bash
brew install bigwig-club/brew/upic --cask
```

### 3. Download from github
 Click [release](https://github.com/gee1k/uPic/releases) to download.
