### ISSUE TITLE
[New Feature] 建议支持 Amazon S3 图片和文件上传

### ISSUE THREAD

**Issue by huhuhang** [gee1k/uPic#21]
**Is your feature request related to a problem? Please describe.**

国内对象储存限制太多，绑定域名必须备案，七牛等开始不支持测试域名。AWS 的体验真的很好，建议支持 S3 对象储存服务。如果支持难度较高，建议应用收费。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gee1k** [comment]
Amazon S3 的支持已经加了，还没有发布。
下个版本发布时会有😎

**Comment by gee1k** [comment]
可以加微信群或者tg群沟通

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/62101704-eb284900-b2c8-11e9-91a6-30f30da9fbb9.png)

**Comment by huhuhang** [comment]
太赞了！

**Comment by gee1k** [comment]
Close by [@v0.9.0](https://github.com/gee1k/uPic/releases/tag/v0.9.0)
