### ISSUE TITLE
在AppleStore上买了，打不开，活动监视器里进程在跑，但是跳不出应用程序。m1pro+macOS12.0.1，挺急的，感谢作者！

### ISSUE THREAD

**Issue by W-Java** [gee1k/uPic#213]
**Describe the bug**

**Screenshots**

**Version:** [e.g. 22]

**Additional context**

**Comment by W-Java** [comment]
已解决！！非常感谢！！

**Comment by gee1k** [comment]
不好意思最近家里有点事儿没怎么看 GitHub。 请问是什么问题导致的呢？是 app 的原因吗？

**Comment by thouger** [comment]
??是什么原因呢我也想知道
