### ISSUE TITLE
使用typora验证上传总是失败

### ISSUE THREAD

**Issue by ChenJyuan** [gee1k/uPic#215]
尝试了使用命令行上传
`/Applications/uPic.app/Contents/MacOS/uPic -o url -u "/Applications/Typora.app/Contents/Resources/TypeMark/assets/icon/icon_512x512.png" "/Applications/Typora.app/Contents/Resources/TypeMark/assets/icon/icon_256x256.png"`

结果显示

`
Uploading ...
Uploading 1/2
Uploading 2/2
Output URL:
Invalid request.

"sha" wasn't supplied.
Invalid request.

"sha" wasn't supplied.
`

**Comment by gee1k** [comment]
这个错误应该是你用的 Github、且文件名重复了。已经上传过同名文件
