### ISSUE TITLE
Upload Imgur images to user account rather than anonymously/or give an option.

### ISSUE THREAD

**Issue by drankush** [gee1k/uPic#218]
Problem: I'm always frustrated when I can't find those Imgur pics uploaded to my user account although it uses my Client ID, because uPic uploads images anonymously.

Solution:
Instead of sending a "CLIENT-ID" header, you need to send a "Bearer" header, with the token that you receive by using imgur's oauth 2 api. This allows you to post images to a user's account, whereas by providing the client id, it will post anonymous images. The code looks like this:
req.add_header("Authorization", "Bearer " + imgur_access_token)

**Comment by gee1k** [comment]
Yes, I know this, but currently, uPic does not integrate OAuth 2.0 Callback.

But you can do this by customizing the Host. The following tutorial is available for reference.

1. Go to [https://api.imgur.com/oauth2/addclient](https://api.imgur.com/oauth2/addclient) to register a new application, `Authorization type` and select `OAuth 2 authorization without a callback URL`.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/12059800/159420170-89ff6f77-27d2-4f4d-acc0-4bc03bdda550.png">


2. After registration, save `client_id`, replace this URL, and open it in your browser. `https://api.imgur.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&response_type=token&state=APPLICATION_STATE`

3. Accept the authorization in the new page returned by the browser, it will automatically jump to a new URL, find `access_token` from the address bar, and copy it down

> Like this:`https://imgur.com/?state=APPLICATION_STATE#access_token=bb4db102ebdb91fe81asfs9a25db115a22a9a1ae5f1&expires_in=315360000&token_type=bearer&refresh_token=c6564cdeee89f58c77db6f4b52121e8ac8ea92cd&account_username=gee1k&account_id=112786303`

access_token is: `bb4db102ebdb91fe81asfs9a25db115a22a9a1ae5f1`

4. The configuration in uPic is as follows
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12059800/159419896-67f4f75b-2237-4c71-86ea-615736c505e2.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/12059800/159419920-d939be59-2c4d-4a59-9641-8f568d002cd0.png">
