### ISSUE TITLE
[New Feature] 自定义图床配置支持 icloud 同步

### ISSUE THREAD

**Issue by tobemaster56** [gee1k/uPic#219]
虽然现在自定义图床配置，支持导入导出

<img width="347" alt="image" src="https://user-images.githubusercontent.com/8998761/159860723-3919e0e3-d51f-4805-8c8a-60bbe4fa3124.png">

不过如果，支持 iCloud 同步来说，对于有多台 Mac 设备的人来说，会更方便一些。并且 Upic 现在好像也支持 iOS 了，支持 iCloud 同步，可能会增加我购买 iOS 版的意愿。

**Comment by Silentely** [comment]
+1 两个地方 ios与mac都需要我手动配置图床太麻烦了，可以直接icloud同步最好了
