### ISSUE TITLE
[BUG]大哥，你这个太难编译了

### ISSUE THREAD

**Issue by qingmo** [gee1k/uPic#224]
**Describe the bug**
我本来就只想做一个简单的contribute，虽然不是太懂swift，但是我觉得应该能改掉#221 #220 这2个问题，
220中提到的禁止外链情况，我不是太确定，我自己测试了一下，我在本地的Joplin是可以用gitee返回中的download_url。
工程编译问题：
swift版本:5.3.2
xcode版本：12.4
其中：
```
Kingfisher
SnapKit
SwiftyJSON
LaunchAtLogin
CryptoSwift
Alamofire
SwiftyXMLParser
MASShortcut
SotoS3
```
这些模块没有纳入cocoapods的管理范围，其中最坑的是SotoS3完全不支持cocopods。工程中缺少Package.swift，如果用默认的Package.resolved 会因为ide和swift与MASShortcut有冲突问题，望大神是否能加入一个Package.swift直接全部用swiftpm来管理。

**Version:** [e.g. 22]
0.2.1

**Comment by gee1k** [comment]
现在就是用的download_url 

Gitee是因为 API 变动（开始检查User Agent了）。商店最新版已更新，但是非常不建议使用Gitee，因为它会限制访问
