### ISSUE TITLE
[BUG]码云图床配置后验证失败

### ISSUE THREAD

**Issue by parcool** [gee1k/uPic#226]
<img width="602" alt="截屏2022-04-18 16 52 45" src="https://user-images.githubusercontent.com/12092478/163783784-da7accce-f68b-4858-91cb-7cfc2f812c8d.png">
<img width="722" alt="截屏2022-04-18 16 53 07" src="https://user-images.githubusercontent.com/12092478/163783800-2a06193d-c8a6-4d51-9165-bb41337438a2.png">
仓库也已经初始化：
<img width="1048" alt="截屏2022-04-18 16 54 13" src="https://user-images.githubusercontent.com/12092478/163783855-38ad7ede-f211-4d88-a3ca-7aa7d0d7cf34.png">

**Comment by parcool** [comment]
`uPic`文件夹是我手动在码云创建的。

**Comment by csccoder** [comment]
最近 我码云也上传不上去了。换了token也不行

**Comment by wis1997** [comment]
mac 系统的上传到 gitee 失败，以前是正常的，突然不能用了，有一阵了

**Comment by Zomnus** [comment]
> mac 系统的上传到 gitee 失败，以前是正常的，突然不能用了，有一阵了

连验证都过不了了
![image](https://user-images.githubusercontent.com/9277837/164583737-67e670be-e18b-4c37-9750-09573aa9776c.png)

**Comment by gee1k** [comment]
Gitee API 变动。商店最新版已更新，但是非常不建议使用Gitee，因为它会限制访问
