### ISSUE TITLE
[BUG]没有通知，截图并上传方式错误 

### ISSUE THREAD

**Issue by RoseauHan** [gee1k/uPic#23]
**Describe the bug**
1、上传成功后没有通知提示，在设置-通知中也找不到upic
2、选择截图并上传方式后，截到的图偶尔是桌面图层的图片，而不是当前最顶层的应用图片。
3、快捷键偶尔没有应答

**Screenshots**
例如当我在
![pic](https://raw.githubusercontent.com/RoseauHan/upic-upload/master/AaeHd6.png)
这里截图的时候，上传完竟然是
![image](https://user-images.githubusercontent.com/31185165/62922987-513fc080-bddf-11e9-878e-10b730b5293d.png)

**Version:** [e.g. 22]
版本号：0.10.3
系统版本： Mac os Catalina 10.15 Beta 

**additional**
使用 homebrew安装。
不知是Catalina 测试版的问题，还是软件适配的问题。

**Comment by gee1k** [comment]
https://github.com/gee1k/uPic/releases/tag/v0.10.4
