### ISSUE TITLE
0.10.4版本中码云图床失效

### ISSUE THREAD

**Issue by vanishcode** [gee1k/uPic#25]
mojave 10.14.4
upics 0.10.4
码云参数配置无误，点击上传后没反应，未提示成功或失败，但使用0.10.0版本成功上传。

**Comment by gee1k** [comment]
上传是没问题的，应该是通知的问题。你先升级到v0.10.5版本看看。
如果上级到v0.10.5还是没有上传成功通知，可以按照以下方法简单操作以下即可。

[上传完成没有通知解决](https://github.com/gee1k/uPic/blob/v0.10.5/README-cn.md#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

![image](https://user-images.githubusercontent.com/12059800/63139696-c692d780-c011-11e9-88ca-61b5e85cd571.png)
