### ISSUE TITLE
[New Feature]在finder中集成上传选项

### ISSUE THREAD

**Issue by CyshallChan** [gee1k/uPic#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![uPic功能建议](https://i.loli.net/2019/08/20/kMOsJtw5aUFKARL.png)
RT，类似dropbox这种。

**Comment by gee1k** [comment]
是有的。必须是在文件上右键，文件夹不行哦。
![image](https://user-images.githubusercontent.com/12059800/63328921-94f87400-c363-11e9-8c11-28e617c935a6.png)


如果你的右键菜单里没有，请检查一下设置是否开启了。
![image](https://user-images.githubusercontent.com/12059800/63329117-ef91d000-c363-11e9-82d0-edcffbc8db54.png)

**Comment by CyshallChan** [comment]
好的，不过这个功能已经知道了，只不过如果能像dropbox那样直接有个图标选项可能会更方便点。

**Comment by gee1k** [comment]
也可以加上

**Comment by gee1k** [comment]
我抽空加上吧

**Comment by CyshallChan** [comment]
好的，非常感谢。

**Comment by gee1k** [comment]
你也可以加微信或者tg群交流

**Comment by CyshallChan** [comment]
已加。

**Comment by gee1k** [comment]
@CyshallChan 最新版 v0.11.1已经在 Finder 菜单栏中增加了上传按钮哦
