### ISSUE TITLE
[BUG]今天2天电脑都打不开这个软件了

### ISSUE THREAD

**Issue by einsqing** [gee1k/uPic#29]
[BUG]今天2天电脑都打不开这个软件了

**Comment by nlnlnull** [comment]
+1

**Comment by gee1k** [comment]
@einsqing @nlnlnull 在排查原因。我自己也遇到了好几个软件都打不开了

**Comment by gee1k** [comment]
@einsqing @nlnlnull 请更新到最新版，[#V0.11.1](https://github.com/gee1k/uPic/releases/tag/v0.11.1)
