### ISSUE TITLE
[New Feature]上传文件的时候，可以随机命名嘛？

### ISSUE THREAD

**Issue by fyzzy1943** [gee1k/uPic#30]
比如用微信截图以后，名字后面会带@2x，这样可能会触发图床的动作，能否增加一个随机命名的规则呢，就像截图一样。

**Comment by gee1k** [comment]
可以的，图床配置里域名输入框后面有一个更多设置，里面有的😅

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/64120799-c47d9680-cdcf-11e9-9eae-e6d01b6a33c4.png)

**Comment by fyzzy1943** [comment]
原来如此。。之前没有看到，多谢啦
