### ISSUE TITLE
有没有支持的自定义图床api的开源库推荐？

### ISSUE THREAD

**Issue by andyhuai** [gee1k/uPic#33]
自建图床的话，对PHP确实不太熟悉，有没有比较的api的程序推荐？
最好是php的，不要数据库的

**Comment by gee1k** [comment]
随便用一个 web 框架就行，Laravel 啥的都可以

**Comment by andyhuai** [comment]
@gee1k 
java，go，node啥的都还能搞一下，php真心不会

**Comment by gee1k** [comment]
@andyhuai 都可以的，服务端没有限制，提供接口就行。nodejs 、Java、Go 都没问题
