### ISSUE TITLE
[BUG]上传提示Condition key q-ak doesn't match

### ISSUE THREAD

**Issue by Caelebs** [gee1k/uPic#34]
**Describe the bug**
腾讯云存储，之前可以上传，这两天上传提示Condition key q-ak doesn't match the value *
检查了腾讯云控制台的密钥，是正确的，也刷新过密钥，还是无法上传呢
**Screenshots**

**Version:** [e.g. 22]
0.12.0
**Additional context**

**Comment by gee1k** [comment]
还是这样吗？我这里测试是可以的 https://svend-1251277638.cos.ap-shanghai.myqcloud.com/sfd/2019-09-28-ieFVvz.png

或着你是在什么特定情况下才会出现吗？

<img width="580" alt="image" src="https://user-images.githubusercontent.com/12059800/65814412-eb36bd80-e213-11e9-8b8a-0911cca55b5b.png">

**Comment by Caelebs** [comment]
不好意思才看到邮件，依然这样，重装过软件还是这样，差不多就是头一天晚上还能正常上传，第二天上传就报这个了，但是同样的配置信息在其他软件下是可以正常上传的[cid:493D18661E56971E71E2B37BEF810499]

 原始邮件
发件人: Svend<notifications@github.com>
收件人: gee1k/uPic<uPic@noreply.github.com>
抄送: Caelebs<yuyizhix@outlook.com>; Author<author@noreply.github.com>
发送时间: 2019年9月28日(周六) 17:18
主题: Re: [gee1k/uPic] [BUG]上传提示Condition key q-ak doesn't match (#34)


还是这样吗？我这里测试是可以的 https://svend-1251277638.cos.ap-shanghai.myqcloud.com/sfd/2019-09-28-ieFVvz.png

或着你是在什么特定情况下才会出现吗？

[image]<https://user-images.githubusercontent.com/12059800/65814412-eb36bd80-e213-11e9-8b8a-0911cca55b5b.png>

**Comment by gee1k** [comment]
@Caelebs 你好！
问题已经修复，请安装最新版 [v0.12.1](https://github.com/gee1k/uPic/releases/tag/v0.12.1)。

**Comment by Caelebs** [comment]
昨晚下了新版本测试了一下可以正常上传了，感谢大佬
