### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lebonnuit** [gee1k/uPic#35]
**Describe the bug**
无法上传gif
尝试了imgur chrome插件，上传的格式是gif，但是用upic的时候貌似默认都是jpg？
然后尝试了github，smms都是一样的情况，是否我配置错误？

**Version:** [e.g. 22]

**Comment by gee1k** [comment]
我这里上传 gif 是正常的。不知道你是用的什么方式上传的。
是从本地文件上传的还是从浏览器等地方拖拽上传的

https://i.imgur.com/gx9qPFg.gif

**Comment by gee1k** [comment]
如果是从浏览器直接拖拽到菜单栏上传的那的确是会变成jpg。这个没办法，浏览器里的gif 拖出来到第三方app会自动被转换为jpg

可以先下载到本地，然后上传
