### ISSUE TITLE
[New Feature]输出格式希望添加正则表达式自定义功能

### ISSUE THREAD

**Issue by JellyL** [gee1k/uPic#36]
输出格式希望添加正则表达式自定义功能，以满足不同需要。
例如我的typora直接粘贴软件的markdown链接无法显示图片，因为软件的md链接没有添加`http://`前缀（而有些人可能需要`https://`）所以不被显示。

**Comment by gee1k** [comment]
@JellyL 输入URL没有HTTP或者HTTPS 是因为你在配置图床的时候 域名中没有写 
<img width="580" alt="image" src="https://user-images.githubusercontent.com/12059800/66804782-f8fb7b00-ef55-11e9-8b99-8d049b700cb0.png">

**Comment by gee1k** [comment]
如图，域名应填写完整，至于是 http 还是 https 则是看你自己的服务
