### ISSUE TITLE
上传历史能显示图片

### ISSUE THREAD

**Issue by L1cardo** [gee1k/uPic#37]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
上传历史能显示图片，类似于下图

![image](https://user-images.githubusercontent.com/33802186/67115217-486cd000-f210-11e9-8560-029e3b5f23ab.png)
![image](https://user-images.githubusercontent.com/33802186/67115339-8d910200-f210-11e9-9afe-82db7a2427e2.png)

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/67137708-1a1cde00-f26c-11e9-9b62-9c9a91efc11c.png)

由于 uPic 是不限制上传文件的类型的，所以上传历史如果直接显示图片的话，当文件不是图片就会有问题。
