### ISSUE TITLE
uPic无法在github中上传文件夹

### ISSUE THREAD

**Issue by 3xp10it** [gee1k/uPic#38]
请问uPic是否考虑支持快捷键上传已经复制到剪切板中的文件夹至github?目前我尝试是失败的,希望能够支持上传文件夹至github,将带来较好的使用体验.

**Comment by gee1k** [comment]
快捷键上传已经复制到剪切板中的文件是支持的，暂时不支持文件夹

**Comment by gee1k** [comment]
目前新版已经支持文件夹上传
https://github.com/gee1k/uPic/releases/tag/v0.18.0
