### ISSUE TITLE
MiniO 的支持

### ISSUE THREAD

**Issue by gumutianqi** [gee1k/uPic#48]
> MinIO is an object storage server released under Apache License v2.0. It is compatible[1] with Amazon S3 cloud storage service. It is best suited for storing unstructured data such as photos, videos, log files, backups and container / VM images. Size of an object can range from a few KBs to a maximum of 5TB.

所以，MinIO 的支持也是很有必要，开源免费，私有化部署，AWS S3 和阿里云 OSS 的替代品，七牛的对象存储也是参考了 MinIO 的 API 的

**Comment by gee1k** [comment]
我去看看

**Comment by PoplarYang** [comment]
1. minio 支持标准的s3
2. 部署方便，维护方便，适合私有部署

其实，upic本身支持aws s3，你只需要在s3的基础上支持`endpoint`和`region`可以自定义应该就可以实现，这样一堆支持s3协议的对象存储都可以支持了。

有一点要注意，对象存储bucket中的文件在s3下默认都是不能公开访问的，上传时需要给这个图片单独加个public访问权限。

**Comment by gee1k** [comment]
v0.19.0 已支持

**Comment by remember-5** [comment]
请问有minio上传使用文档吗？

**Comment by remember-5** [comment]
## 环境描述

### 插件版本
Minio Version `2020-05-29T14:08:49Z`
uPic Version `0.19.3`

### minio配置
Minio使用了nginx代理，访问地址为 http://xx.xx.xx.xx/minio
新建了bucket名称为 `bucket1`
配置已经改为Read And Write

![image](https://user-images.githubusercontent.com/31730796/85191772-a9462e00-b2f2-11ea-9d5a-a29d12149aec.png)

测试网页端正常上传文件，看了下network中的上传是`put`请求 
 http://xx.xx.xx.xx/minio/upload/bucket1/xxx.png

### uPic配置
![image](https://user-images.githubusercontent.com/31730796/85191918-3d17fa00-b2f3-11ea-8ab9-ac8ae6713912.png)

点击`验证`后，使用`charles`抓包看到以下内容，发现是403

![image](https://user-images.githubusercontent.com/31730796/85191964-5faa1300-b2f3-11ea-9150-ca0838398514.png)

nginx日志打印也转发成功了,access.log日志内容如下
```
xx.xxx.xx.xx - - [20/Jun/2020:12:44:50 +0800] "PUT /minio/upload/bucket1/Or6QPX.png HTTP/1.1" 403 276 "-" "uPic/0.19.3 (com.svend.uPic; build:20200612; macOS 10.13.6) Alamofire/5.0.2"
```

请问这样使用是否正确呢？ 我该如何去排查这个错误呢，能有大佬指点一下吗，谢谢

**Comment by PoplarYang** [comment]
@remember-5 minio 测试过，你可以联系我 echohiyang@foxmail.com
