### ISSUE TITLE
[历史记录]增加已上传图片预览

### ISSUE THREAD

**Issue by lchecho** [gee1k/uPic#49]
首先给作者点个赞，很棒的软件，而且只有10几M，这就很nice了！
建议可以像ipic一样，已上传图片预览列表，可以很直观的看到图片，点击后复制链接这样，不知道好不好实现。
加油，付费了绝对支持！

**Comment by gee1k** [comment]
@lchecho 感谢支持！
你说的功能已经存在的。鼠标放到 URL 上会出现预览，点击会复制。
![image](https://user-images.githubusercontent.com/12059800/69201416-2c46b080-0b79-11ea-8131-8b8aab73a93c.png)

**Comment by gee1k** [comment]
@lchecho 暂时没有考虑付费，能帮助到你就好🤓
