### ISSUE TITLE
【支持图床】添加cloudinary图床服务

### ISSUE THREAD

**Issue by gee1k** [gee1k/uPic#5]
添加cloudinary图床服务

**Comment by gee1k** [comment]
相关链接:
https://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api
https://cloudinary.com/documentation/upload_images#generating_authentication_signatures

**Comment by ncepuwanghui** [comment]
@gee1k 请教下，uPic现在支持Cloudinary了吗，我再V0.18.2中没看到，自定义图床好像也无法配置
