### ISSUE TITLE
[New Feature]请更新阿里云支持的Region

### ISSUE THREAD

**Issue by stelalae** [gee1k/uPic#60]
目前通过brew安装的版本里阿里云的Region不是最新的，这里有最新完整的Region：https://help.aliyun.com/document_detail/31837.html

**Comment by gee1k** [comment]
巧了，我刚提交完代码没多久。就看到了这个问题😂

![image](https://user-images.githubusercontent.com/12059800/71263171-565be000-237c-11ea-9d6c-93f96b85ced0.png)

**Comment by gee1k** [comment]
我会尽快发布新版
