### ISSUE TITLE
更新太慢[BUG]

### ISSUE THREAD

**Issue by liuliuzx** [gee1k/uPic#65]
大佬，老是弹出提示要更新，可是我更新的速度1分种才121kb啊。。想更新都更新不了啊

**Comment by gee1k** [comment]
这不是 bug，是你的网络链接 Github 太慢了。更新源都在 github。
你可以考虑开个代理，或者手动下载覆盖更新

请参考文档：https://github.com/gee1k/uPic/blob/master/README-cn.md#-%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85

![image](https://user-images.githubusercontent.com/12059800/71501887-f5666780-28a7-11ea-92c9-0cc38bc57a4c.png)
