### ISSUE TITLE
[New Feature]SM.MS的上传有可能支持自定义到自己的帐号么？

### ISSUE THREAD

**Issue by SharkIng** [gee1k/uPic#66]
就和例如 Imgur 一样，运行输入自己的API Key等？如果为空则使用开发者默认的

**Comment by gee1k** [comment]
SM.MS 现在使用的是 V1 的API。都是匿名上传的。V2 的 API 是使用用户自己的 Key 等。已经有计划支持。
在这之前，你可以使用自定义图床来配置使用

![image](https://user-images.githubusercontent.com/12059800/71565287-364cbf00-2ae8-11ea-94ce-d5a01818494d.png)

![image](https://user-images.githubusercontent.com/12059800/71565296-42d11780-2ae8-11ea-8970-f090b64e56ca.png)

**Comment by SharkIng** [comment]
好的谢谢
