### ISSUE TITLE
[New Feature] 支持设置微博图床的域名

### ISSUE THREAD

**Issue by fjc0k** [gee1k/uPic#67]
**Is your feature request related to a problem? Please describe.**
微博图床目前大部分域名都是防盗链的，包括 uPic 使用的 ws1，但其存在小部分域名可以外链，比如：`tva1.sinaimg.cn`，因此，建议加上自定义域名，默认为 ws1 即可。

**Describe the solution you'd like**
自定义域名：ws1.sinaimg.cn

**Comment by gee1k** [comment]
可以
