### ISSUE TITLE
截图怎么控制宽高？

### ISSUE THREAD

**Issue by einsqing** [gee1k/uPic#7]
截图怎么控制宽高？

**Comment by gee1k** [comment]
截图操作是拉框截图的
控制宽高是什么意思？🤔

**Comment by einsqing** [comment]
@gee1k 就是我想截出某个尺寸图，或者某个比例的图

**Comment by gee1k** [comment]
> @gee1k 就是我想截出某个尺寸图，或者某个比例的图

这个目前是不支持的哦，只能拉框截图
