### ISSUE TITLE
如何找到上传到imgur的图片

### ISSUE THREAD

**Issue by Dylan-H-Wang** [gee1k/uPic#70]
你好，
按照步骤我已经能够成功上传图片到imgur上，并且也能够复制markdown link。但是为什么我在我自己的imgur页面内找不到图片呢？

**Comment by gee1k** [comment]
通过 Client ID 上传的 API 是匿名上传的，不会保存到自己的账户。如果需要存到自己账户需要进行更复杂的鉴权
