### ISSUE TITLE
[BUG] macOS 无法启动

### ISSUE THREAD

**Issue by tinyRatP** [gee1k/uPic#71]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/15377472/71886095-9b528580-3176-11ea-9550-8ca0b4036caf.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/15377472/71886124-a2799380-3176-11ea-8dce-b28f327c0097.png">
重启系统过后依然如此。

**Comment by gee1k** [comment]
嗯，这个问题正在解决。你可以在`活动监视器`里看看有没有进程，并结束进程。重新开启

**Comment by gee1k** [comment]
请下载最新版
