### ISSUE TITLE
[BUG]JPG图片压缩后比原文件还大

### ISSUE THREAD

**Issue by ncepuwanghui** [gee1k/uPic#73]
**Describe the bug**
原文件大小2.9MB，使用uPic上传到阿里云OSS后，显示大小为3.12MB
PNG图片压缩正常，PNG原图60多KB，上传至OSS后10KB左右
**Screenshots**
原图信息：
![1578642510533](https://user-images.githubusercontent.com/6895399/72135432-6f771000-33c1-11ea-9771-644119b88718.jpg)
上传至OSS后的文件信息：
![WX20200110-154753](https://user-images.githubusercontent.com/6895399/72135445-7b62d200-33c1-11ea-9639-9c6d616ee94c.png)
uPic配置参数：
![Xnip2020-01-10_15-58-56](https://user-images.githubusercontent.com/6895399/72135726-25daf500-33c2-11ea-9851-889aacdd73b8.jpg)

**Version:** [e.g. 22]
uPic 0.16.4

**Additional context**

**Comment by gee1k** [comment]
好的，我会再优化优化。我测试下来大部分还是正常压缩变小的，有部分会变大
