### ISSUE TITLE
[BUG]更新出现错误

### ISSUE THREAD

**Issue by fguby** [gee1k/uPic#74]
![image](https://user-images.githubusercontent.com/33178517/73903702-b844ba80-48d4-11ea-8e97-4832f34d0ff2.png)

更新了很多次，每次都在重启时出现错误

**Comment by fguby** [comment]
![WechatIMG5](https://user-images.githubusercontent.com/33178517/73903833-0a85db80-48d5-11ea-8de6-8d8d4f4f7251.jpeg)

**Comment by gee1k** [comment]
你现在版本是多少

**Comment by fguby** [comment]
卸载后重新下载了，版本号我也忘了
