### ISSUE TITLE
[New Feature]增加主机别名

### ISSUE THREAD

**Issue by Eccon** [gee1k/uPic#75]
**Is your feature request related to a problem? Please describe.**

配置多个同类型图床时，Host 显示的名称相同，造成混淆，难以区分

---

**Describe the solution you'd like**

增加 Host 别名功能，配置 Host 时可以配置一个自定义别名，方便使用时区分

---

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/18576718/74920999-0941cc00-5408-11ea-82fb-aeae029c3891.png)

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/75009547-e8d04b00-54b5-11ea-9a04-32de6dd5c455.png)

单击一下需要修改的名称即可修改
