### ISSUE TITLE
是否可以考虑上传PNG图片不要转换成JPG

### ISSUE THREAD

**Issue by Rhinocros** [gee1k/uPic#76]
是否可以考虑Github上传PNG图片不要转换成JPG，或者增加个开关
上传png图标需要保持背景透明

**Comment by gee1k** [comment]
你是否是老版本且开启了压缩功能？
新版本 png 压缩是不会转换为 jpg 的

**Comment by Rhinocros** [comment]
我用的最新版本，选择的不压缩

**Comment by gee1k** [comment]
我这里实测不会转成jpg的，你换一张图片试试呢！是不是这张图有点问题

**Comment by Rhinocros** [comment]
![image](https://tvax3.sinaimg.cn/large/006Rm27Qly1gcc7pk8fzfj30rg0mm7mv.jpg)
这是历史记录，图标源文件都是png格式的，上传之后都变成了jpg
我是剪贴板上传的，跟这个有关系吗

**Comment by Rhinocros** [comment]
搞明白了，是我的问题
如果直接上传本地图片，或者复制图片地址上传就会保持PNG，点复制图片再上传就会变成JPG
还是感谢回复我的问题，如果可能的话，最好能改动一下会更方便
谢谢

**Comment by gee1k** [comment]
你能否提供一下录屏看看呢？

我本地的png文件拷贝到剪切板上传也是不会变为png的
直接截图后上传也是不会变的
https://raw.githubusercontent.com/gee1k/oss/master/uPic/1.png

https://raw.githubusercontent.com/gee1k/oss/master/uPic/3pKZur.png

**Comment by Rhinocros** [comment]
对，你说的这两种情况是不会变jpg的
唯独只有在网页里的png上点右键，然后复制图片上传的时候会变成jpg
右键复制图片地址是没问题的
![image](https://tva2.sinaimg.cn/large/006Rm27Qly1gcc8dcjbdjj30c605ogpx.jpg)

**Comment by gee1k** [comment]
好的。了解了，我抽时间看看这个问题

**Comment by gee1k** [comment]
这个问题暂时还没办法解决，从浏览器复制出来的图片我只能拿到jpg 格式，我去测试了一下其他软件，微信等等都是这样

**Comment by Rhinocros** [comment]
好的吧，能找到正常使用的办法就可以了，谢谢
另外问个问题，最近正在学swift语言，有什么推荐的方法或者课程吗

**Comment by gee1k** [comment]
Swift 资料比较少。推荐一个 https://swiftgg.gitbook.io/swift/
