### ISSUE TITLE
[New Feature] Support the lsky pro

### ISSUE THREAD

**Issue by syhily** [gee1k/uPic#77]
[lsky pro](https://github.com/wisp-x/lsky-pro) could be integrated by using the uPic's custom host. It's quite easy to add this backend by using its [rest API](https://pic.iqy.ink/index/api.html).

So I would like to ask could upic add this picture service support officially.

**Comment by gee1k** [comment]
Well, it seems like a lot of people use lsky. I'll check it out

**Comment by gee1k** [comment]
Supported in v0.17.0
