### ISSUE TITLE
[New Feature] 几个 Feature 建议

### ISSUE THREAD

**Issue by ysmintor** [gee1k/uPic#79]
**Is your feature request related to a problem? Please describe.**
历史记录清理后，没有图片，可否增加类型 PicGo 图库模式。
上传前自动添加水印功能
图库中图片删除同步（Github 删除同步）

**Describe the solution you'd like**

**Additional context**
都是常用的功能，希望能慢慢添加。比 PicGo 好用，PicGo 剪切板上传在 GithubPlus 上传那总出现问题，这个没有，稳定性高！

**Comment by gee1k** [comment]
uPic 不会去管理服务端文件的。只做上传工具
