### ISSUE TITLE
[New Feature] 支持 base64 方式上传文件

### ISSUE THREAD

**Issue by fjc0k** [gee1k/uPic#80]
## 应用场景

某些接口可能只支持 base64 上传，故而提出此需求。

## 可能的实现方案

可在 `文件字段名` 下加个字段 `是否将文件 base64 编码后上传`。

**Comment by fjc0k** [comment]
同时，如果实现了，还得加个 `mime_type` 变量，因为一般 base64 上传的都会手动指定文件类型。

**Comment by gee1k** [comment]
之前也考虑过base64，下版本加上

**Comment by gee1k** [comment]
请看 v0.18.0 
https://github.com/gee1k/uPic/releases/tag/v0.18.0
