### ISSUE TITLE
[New Feature] Upload images within directories

### ISSUE THREAD

**Issue by mxmzb** [gee1k/uPic#81]
**Is your feature request related to a problem? Please describe.**

I use uPic to upload image files to my S3, so I can link them from my blog. I'd like to have my uploaded files properly structured in directories (e.g. article slugs). To do so, I need to create a new host or slightly change the current host. 

**Describe the solution you'd like**

I would love, if I could upload a directory of images with uPic. That way, images would be stored within a predefined file structure.

**Describe alternatives you've considered**

One alternative would be to have a faster access to change the file path of the upload, so you wouldn't have to go through the settings but change it directly from the drop-down menu or similar.

Honestly, I quite like that idea, too (and it would be rather a UI change than a functional change, by just providing another, easier accessible place to set the path).

**Comment by gee1k** [comment]
Good advice. It will come soon

**Comment by gee1k** [comment]
New version released.
https://github.com/gee1k/uPic/releases/tag/v0.18.0
