### ISSUE TITLE
[New Feature] Don't auto-update 

### ISSUE THREAD

**Issue by tinyRatP** [gee1k/uPic#82]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Is it the better way to set a switch that the user can decide if upic can auto-update.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by gee1k** [comment]
The update program USES Sparkle implementation and should be optional not to automatically check for updates when first prompted
