### ISSUE TITLE
[BUG]显示图标会更改其他范围的图标，例如，挂在磁盘

### ISSUE THREAD

**Issue by 1021683053** [gee1k/uPic#83]
**Describe the bug**
显示图标会更改其他范围的图标，例如，挂在磁盘

**Screenshots**
![image](https://user-images.githubusercontent.com/7711802/76272886-6fa76500-62b7-11ea-91c0-14b96a9298b4.png)

**Version:** 
0.18.0

**Comment by gee1k** [comment]
无法复现。
但是网上有不少关于这种问题的帖子，这个问题应该是属于 macos 系统问题。包括 onedrive、dropbox 等app在内很多都会出现类似现象
