### ISSUE TITLE
[New Feature]可否增加淘宝图片空间？

### ISSUE THREAD

**Issue by Seegar** [gee1k/uPic#85]
感谢！
小白请求能否增加淘宝图片空间。
我不太确定能否实现，只是觉得淘宝图片空间外链还蛮好用的，目前就是在用淘宝图片空间，但是上传比较繁琐，要先打开网页去登录淘宝账号然后再去上传生成链接，现在还没看到过关于图片空间的任何上传应用。
辛苦了。

**Comment by gee1k** [comment]
不会
