### ISSUE TITLE
[New Feature] Support Lutim

### ISSUE THREAD

**Issue by dertuxmalwieder** [gee1k/uPic#87]
Lutim is the software behind a few popular image hosters. Now I would like to add `wtf.roflcopter.fr/pics` to uPic. The problem here is that Lutim has two return values for the return value as described [here](https://framagit.org/fiat-tux/hat-softwares/lutim/-/wikis/API):

    https://DOMAIN/["msg", "real_short"]/["msg", "filename"]

It seems that uPic does not support that yet?

**Comment by gee1k** [comment]
Yes, this complex usage is not currently supported. And then I'm going to think about what do I do
