### ISSUE TITLE
[BUG] 图片 URL 不包括协议名时无法拼接出完整的图片地址

### ISSUE THREAD

**Issue by fjc0k** [gee1k/uPic#90]
**Describe the bug**

现有一上传接口，其返回的图片地址没有协议名，类似这样：

```json
{
  "url": "//foo.bar/hello.png"
}
```

于是我在设置的域名处填写 `https:`，但最终生成的地址是 `https:///foo.bar/hello.png`，多了一道 `/`。

因此，建议在程序里对这种情况根据 `API 地址` 使用的协议名将 URL 补充完整。

**Version:** 0.18.1

**Comment by gee1k** [comment]
v0.18.2 已修复自定义域名重复补充 // 的问题
