### ISSUE TITLE
[New Feature]后续能否支持压缩到指定的分辨率？

### ISSUE THREAD

**Issue by moriwang** [gee1k/uPic#92]
目前的图片压缩功能只有百分比的选项，对于大图小图一视同仁我觉得有点不方便。能不能有一个机制，长宽像素值或图片大小超过一定数值后，才启动压缩功能。

另外就是能否压缩到指定的长宽。比如我用 Mac 自带的截图，一张全屏的图片不加设置是 3360 × 2100，但是在发布文章的时候，往往使用 1920x1080 已经很足够了。

**Comment by gee1k** [comment]
建议配合，阿里云、腾讯云、七牛云等等服务商提供的更完备的图片处理功能来实现
