### ISSUE TITLE
直接用系统快捷键复制的屏幕截图无法从剪贴板上传。

### ISSUE THREAD

**Issue by BillChen2K** [gee1k/uPic#95]
直接用系统快捷键复制的屏幕截图无法从剪贴板上传。

比如使用 control + command + shift + 4 可以将屏幕中的某一个区域复制到剪贴板中，但这时在 uPic 中选择上传到剪贴板则没有效果。

目前似乎还是只能直接用 uPic 的从屏幕截图上传功能，有没有办法让 uPic 直接读取系统截图剪贴板中的 tiff 数据呢？

比如使用系统自带的截图到剪贴板功能后，使用 iPaste 查看剪贴板：

![image](https://user-images.githubusercontent.com/11037722/79434710-56ee4580-8001-11ea-8a36-0ce762c97585.jpeg)

但此时无法使用 uPic 的从剪贴板上传功能。只有直接复制硬盘或网页上的文件时才有效。

uPic 版本：0.18.2
macOS 版本：10.15.4

**Comment by gee1k** [comment]
测试是可以的

![屏幕录制2020-04-17 12 38 46 2020-04-17 12_39_57](https://user-images.githubusercontent.com/12059800/79532737-94f27480-80a8-11ea-8cae-39dbd8e87f13.gif)

**Comment by BillChen2K** [comment]
我排查了一下，也许是因为修改过屏幕截图的默认格式。苹果默认的截图格式为 png，但文件太大，我曾经把格式改成了 jpg 以节省磁盘空间：
```sh
defaults write com.apple.screencapture type jpg;
killall SystemUIServer
```
执行以上命令后再从剪贴板上传就没有反应了。通过`sh
defaults write com.apple.screencapture type png
killall SystemUIServer
`改回 png 又可以了。
