### ISSUE TITLE
[BUG]试了一下 还是不能用啊 开发者大佬

### ISSUE THREAD

**Issue by hlf2016** [gee1k/uPic#97]
**Describe the bug**

**Screenshots**
点击打开，提示让联系开发者更新

**Version:** [e.g. 22]
1.9.1
**Additional context**

**Comment by gee1k** [comment]
可以打开的，你看看隐私设置里有没有允许可以设置

**Comment by zronghui** [comment]
同，回退到18.2 也打不开了

**Comment by zronghui** [comment]
可以了，又重新安装了 19.1
